"""Render QUEUE.md for the Pro's Codex orchestrator, and run acceptance
checks on claimed tasks so a task closes the moment its proof exists."""

from __future__ import annotations

import os
import pathlib

from . import acceptance
from .schema import AREAS, Task, now_iso
from .store import Store, StoreError

DEFAULT_OUT = pathlib.Path.home() / ".codex" / "workstream-results" / "QUEUE.md"
STATE_ORDER = ("claimed", "open", "blocked")


def check_claimed(store: Store, actor: str = "queue-render", cwd: pathlib.Path | None = None) -> list[tuple[Task, bool | None, str]]:
    """Check outside the write transaction, then conditionally finish that exact claim."""
    results = []
    if actor != "queue-render":
        raise StoreError("automatic checks require queue-render protocol actor")
    for task in store.list(state="claimed"):
        ok, detail = acceptance.check_task(task, cwd=cwd)
        if ok is None:
            results.append((task, None, detail))
            continue
        try:
            current = store.finish_check(task.id, expected_revision=task.revision,
                                         claim_token=task.claim_token, ok=ok, detail=detail, actor=actor)
        except StoreError:
            # A pass here would make the unchanged monitor falsely count a close.
            results.append((store.get(task.id) or task, False, "check not committed: claim changed or unavailable"))
            continue
        results.append((current, ok, detail))
    return results


def _cell(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _table(tasks: list[Task]) -> list[str]:
    lines = [
        "| state | id | kind | owner | pri | title | deps | acceptance | last check |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for t in tasks:
        if t.state == "blocked":
            state = f"blocked: {_cell(t.blocked_on)[:80]}"
        elif t.state == "claimed":
            state = f"claimed by {t.claimed_by}"
        else:
            state = t.state
        check = ""
        if t.last_check_at:
            check = f"{'pass' if t.last_check_ok else 'FAIL'} {t.last_check_at} {_cell(t.last_check_detail)[:80]}"
        lines.append(
            f"| {state} | `{t.id}` | {t.kind} | {t.owner} | {t.priority} | {_cell(t.title)} | "
            f"{', '.join(f'`{d}`' for d in t.deps) or ''} | {_cell(t.acceptance.short())[:120]} | {check} |"
        )
    return lines


def render_markdown(store: Store, generated_at: str | None = None) -> str:
    generated_at = generated_at or now_iso()
    counts = store.counts()
    open_tasks = store.list()
    done_recent = store.list(state="done")[-15:]
    out = [
        "# Task queue",
        "",
        f"Generated {generated_at} from `{store.path}` by `ito-queue render`. "
        "Do not edit this file; edit the store with `bin/ito-queue`.",
        "",
        "Rules: claim before working (`ito-queue claim <id> --as <owner>`), one task at a time per owner, "
        "automatic completion requires a current claim-bound v1 receipt; legacy checks require explicit reviewed completion. "
        "Owners: mini-claude, mini-hermes, pro-codex, affaan. "
        "Areas are single-area by design: a task belongs to exactly one of ECC, ITO, PERSONAL, INFRA.",
        "",
        "## Counts",
        "",
        "| state | n |",
        "|---|---|",
    ]
    for state in ("open", "claimed", "blocked", "done", "dropped"):
        out.append(f"| {state} | {counts.get(state, 0)} |")
    out.append("")

    by_owner: dict[str, list[Task]] = {}
    for t in open_tasks:
        by_owner.setdefault(t.owner, []).append(t)
    out += ["## Next up per owner", ""]
    for owner in ("pro-codex", "mini-claude", "mini-hermes", "affaan"):
        tasks = by_owner.get(owner, [])
        claimed = [t for t in tasks if t.state == "claimed"]
        ready = [t for t in tasks if t.state == "open" and not store.unmet_deps(t)]
        ready.sort(key=lambda t: (t.priority, t.created_at, t.id))
        line = f"- **{owner}**: "
        parts = []
        if claimed:
            parts.append("claimed " + ", ".join(f"`{t.id}`" for t in claimed))
        if ready:
            parts.append("ready " + ", ".join(f"`{t.id}`" for t in ready[:5]))
        if not parts:
            parts.append("nothing ready")
        out.append(line + "; ".join(parts))
    out.append("")

    for area in AREAS:
        tasks = [t for t in open_tasks if t.area == area]
        if not tasks:
            continue
        tasks.sort(key=lambda t: (STATE_ORDER.index(t.state) if t.state in STATE_ORDER else 9, t.priority, t.created_at, t.id))
        out += [f"## {area} ({len(tasks)} open)", ""]
        out += _table(tasks)
        out.append("")

    if done_recent:
        out += ["## Recently done", ""]
        for t in done_recent:
            receipt = t.receipts[-1] if t.receipts else ""
            out.append(f"- `{t.id}` {_cell(t.title)} ({t.owner}) {_cell(receipt)[:140]}")
        out.append("")
    return "\n".join(out)


def write(store: Store, path: pathlib.Path | None = None, generated_at: str | None = None) -> pathlib.Path:
    path = path or pathlib.Path(os.environ.get("ITO_QUEUE_MD", str(DEFAULT_OUT))).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".md.tmp")
    tmp.write_text(render_markdown(store, generated_at))
    os.replace(tmp, path)
    return path
